nodeLinker: node-modules

changesetIgnorePatterns:
  - "**/*.{test,spec}.{js,mjs,cjs,ts}"

npmScopes:
  dataone:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://clearscoredev.jfrog.io/artifactory/api/npm/npm-public/"
    npmRegistryServer: "https://clearscoredev.jfrog.io/artifactory/api/npm/npm-public/"

yarnPath: .yarn/releases/yarn-3.2.4.cjs